name: '[PSH] Quality Engineering'

on:
  push:
    branches:
      - master
      - main

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      nodeLint: true
      reactTest: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_b2b-orders-history
      nodeSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
